services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Softspring\CmsBundle\Admin\:
        resource: '../../src/Admin/*'
        
    Softspring\CmsBundle\Twig\Extension\Admin\:
        resource: '../../src/Twig/Extension/Admin/*'
        tags: [ 'twig.extension' ]
