services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\CmsBundle\Request\ParamConverter\:
        resource: '../../src/Request/ParamConverter/*'
        tags: [ 'request.param_converter' ]