parameters:
    sfs_cms.admin.sections_version.list_view: '@@SfsCms/admin/section/version_list.html.twig'
    sfs_cms.admin.sections_version.create_view: '@@SfsCms/admin/section/version_create.html.twig'
    sfs_cms.admin.sections_version.delete_view: '@@SfsCms/admin/section/version_delete.html.twig'
    sfs_cms.admin.sections_version.preview_layout_view: '@@SfsCms/admin/section/version_preview_layout.html.twig'
    sfs_cms.admin.sections_version.info_view: '@@SfsCms/admin/section/version_info.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $sectionAutoCompileOnPublish: '%sfs_cms.section.autocompile_on_publish%'
            $sectionSaveCompiled: '%sfs_cms.section.save_compiled%'
            $sectionRecompileEnabled: '%sfs_cms.section.recompile_enabled%'

    Softspring\CmsBundle\Admin\ActionListener\SectionVersion\:
        resource: '../../src/Admin/ActionListener/SectionVersion/*'

    Softspring\CmsBundle\Form\Admin\SectionVersion\:
        resource: '../../../src/Form/Admin/SectionVersion/*'

    sfs_cms.admin.section_version.controller:
        class: Softspring\Component\CrudlController\Controller\CrudlController
        public: true
        arguments:
            $manager: '@Softspring\CmsBundle\Manager\SectionVersionManagerInterface'
            $configs:
                entity_attribute: 'version'
                version_create:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_CREATE'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_INITIALIZE
                    create_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_ENTITY
                    form_prepare_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_FORM_PREPARE
                    form_init_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_FORM_INIT
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_FORM_VALID
                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_APPLY
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_FAILURE
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_VIEW
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CREATE_EXCEPTION
                    success_redirect_to: 'sfs_cms_admin_sections_list'
                    view: '%sfs_cms.admin.sections_version.create_view%'
                    form: '@Softspring\CmsBundle\Form\Admin\SectionVersion\VersionCreateFormInterface'
#                version_import:
#                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_INITIALIZE
#                    create_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_ENTITY
#                    form_prepare_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_FORM_PREPARE
#                    form_init_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_FORM_INIT
#                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_FORM_VALID
#                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_APPLY
#                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_SUCCESS
#                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_FAILURE
#                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_FORM_INVALID
#                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_VIEW
#                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_IMPORT_EXCEPTION
                version_preview:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_PREVIEW'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PREVIEW_INITIALIZE
                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PREVIEW_LOAD_ENTITY
                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PREVIEW_NOT_FOUND
                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PREVIEW_FOUND
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PREVIEW_EXCEPTION
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PREVIEW_VIEW
                    view: '%sfs_cms.admin.sections_version.preview_layout_view%'
                version_lock:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_KEEP'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LOCK_INITIALIZE
                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LOCK_LOAD_ENTITY
                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LOCK_NOT_FOUND
                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LOCK_FOUND
                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LOCK_APPLY
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LOCK_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LOCK_FAILURE
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LOCK_EXCEPTION
                version_recompile:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_RECOMPILE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_RECOMPILE_INITIALIZE
                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_RECOMPILE_LOAD_ENTITY
                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_RECOMPILE_NOT_FOUND
                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_RECOMPILE_FOUND
                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_RECOMPILE_APPLY
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_RECOMPILE_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_RECOMPILE_FAILURE
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_RECOMPILE_EXCEPTION
                version_publish:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_PUBLISH'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PUBLISH_INITIALIZE
                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PUBLISH_LOAD_ENTITY
                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PUBLISH_NOT_FOUND
                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PUBLISH_FOUND
                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PUBLISH_APPLY
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PUBLISH_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PUBLISH_FAILURE
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_PUBLISH_EXCEPTION
#                version_export:
#                    param_converter_key: 'id'
#                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_EXPORT_INITIALIZE
#                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_EXPORT_LOAD_ENTITY
#                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_EXPORT_NOT_FOUND
#                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_EXPORT_FOUND
#                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_EXPORT_APPLY
#                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_EXPORT_SUCCESS
#                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_EXPORT_FAILURE
#                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_EXPORT_EXCEPTION
                version_list:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_VERSIONS'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LIST_INITIALIZE
                    filter_form_prepare_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LIST_FILTER_FORM_PREPARE
                    filter_form_init_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LIST_FILTER_FORM_INIT
                    filter_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LIST_FILTER
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LIST_VIEW
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_LIST_EXCEPTION
                    view: '%sfs_cms.admin.sections_version.list_view%'
#                    view_page: '%sfs_cms.admin.sections_version.list_page_view%'
                    filter_form: '@Softspring\CmsBundle\Form\Admin\SectionVersion\VersionListFilterFormInterface'
                version_clear_compiled:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_CLEAR_COMPILED'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CLEAR_COMPILED_INITIALIZE
                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CLEAR_COMPILED_LOAD_ENTITY
                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CLEAR_COMPILED_NOT_FOUND
                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CLEAR_COMPILED_FOUND
                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CLEAR_COMPILED_APPLY
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CLEAR_COMPILED_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CLEAR_COMPILED_FAILURE
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_CLEAR_COMPILED_EXCEPTION
                version_info:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_INFO'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_INITIALIZE
                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_LOAD_ENTITY
                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_NOT_FOUND
                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_FOUND
                    form_prepare_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_FORM_PREPARE
                    form_init_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_FORM_INIT
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_FORM_VALID
                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_APPLY
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_FAILURE
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_VIEW
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_INFO_EXCEPTION
                    view: '%sfs_cms.admin.sections_version.info_view%'
                    form: '@Softspring\CmsBundle\Form\Admin\SectionVersion\VersionUpdateFormInterface'
                version_delete:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_SECTION_VERSION_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_INITIALIZE
                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_LOAD_ENTITY
                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_NOT_FOUND
                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_FOUND
                    form_prepare_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_FORM_PREPARE
                    form_init_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_FORM_INIT
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_FORM_VALID
                    apply_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_APPLY
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_FAILURE
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_VIEW
                    exception_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_SECTION_VERSIONS_DELETE_EXCEPTION
                    form: '@Softspring\CmsBundle\Form\Admin\SectionVersion\VersionDeleteFormInterface'
                    view: '%sfs_cms.admin.sections_version.delete_view%'
