parameters:
    sfs_cms.admin.blocks.list_view: '@@SfsCms/admin/block/list.html.twig'
    sfs_cms.admin.blocks.list_content_view: '@@SfsCms/admin/block/list-content.html.twig'
    sfs_cms.admin.blocks.create_view: '@@SfsCms/admin/block/create.html.twig'
    sfs_cms.admin.blocks.update_view: '@@SfsCms/admin/block/update.html.twig'
    sfs_cms.admin.blocks.delete_view: '@@SfsCms/admin/block/delete.html.twig'
    sfs_cms.admin.blocks.read_view: '@@SfsCms/admin/block/read.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_cms.entity_manager'
            $blockTypes: [] # '%sfs_cms.block.types%'

    Softspring\CmsBundle\EventListener\Admin\Block\:
        resource: '../../src/EventListener/Admin/Block/*'

    Softspring\CmsBundle\Form\Admin\Block\:
        resource: '../../../src/Form/Admin/Block/Block*'
    
    Softspring\CmsBundle\Manager\BlockManagerInterface:
        class: Softspring\CmsBundle\Manager\BlockManager

    sfs_cms.admin.block.controller:
        class: Softspring\Component\CrudlController\Controller\CrudlController
        public: true
        tags: [ 'controller.service_arguments' ]
        arguments:
            $manager: '@Softspring\CmsBundle\Manager\BlockManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $configs:
                entity_attribute: 'block'
                list:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_BLOCKS_LIST'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_LIST_INITIALIZE
                    filter_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_LIST_FILTER
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_LIST_VIEW
                    view: '%sfs_cms.admin.blocks.list_view%'
                    view_page: '%sfs_cms.admin.blocks.list_content_view%'
                    filter_form: '@Softspring\CmsBundle\Form\Admin\Block\BlockListFilterFormInterface'
                create:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_BLOCKS_CREATE'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_INITIALIZE
                    create_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_ENTITY
                    form_prepare_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_FORM_PREPARE
                    form_init_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_FORM_INIT
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_FAILURE
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_CREATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_blocks_list'
                    view: '%sfs_cms.admin.blocks.create_view%'
                    form: '@Softspring\CmsBundle\Form\Admin\Block\BlockCreateFormInterface'
                update:
                    is_granted: 'PERMISSION_SFS_CMS_ADMIN_BLOCKS_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_INITIALIZE
                    load_entity_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_LOAD_ENTITY
                    not_found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_NOT_FOUND
                    found_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_FOUND
                    form_prepare_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_FORM_PREPARE
                    form_init_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_FORM_INIT
                    form_valid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_SUCCESS
                    failure_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_FAILURE
                    form_invalid_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\CmsBundle\SfsCmsEvents::ADMIN_BLOCKS_UPDATE_VIEW
                    success_redirect_to: 'sfs_cms_admin_blocks_list'
                    view: '%sfs_cms.admin.blocks.update_view%'
                    form: '@Softspring\CmsBundle\Form\Admin\Block\BlockUpdateFormInterface'
