# this is the page base configuration
content:
    revision: 3
    entity_class: 'Softspring\CmsBundle\Entity\Page'
    default_layout: 'default'
    version_seo:
        metaTitle:
            type: translation
        metaDescription:
            type: translation
        metaKeywords:
            type: translation
        canonicalContent:
            type: translatable
            type_options:
                extractable: false
                type: content
                type_options:
                    required: false
    indexing:
        noIndex:
            type: checkbox
            type_options:
                required: false
                default_value: false
        noFollow:
            type: checkbox
            type_options:
                required: false
                default_value: false
        sitemap:
            type: checkbox
            type_options:
                required: false
                attr:
                    data-show-fields-if-checked: 'sitemapChangefreq,sitemapPriority'
                    data-hide-fields-if-unchecked: 'sitemapChangefreq,sitemapPriority'
                default_value: true
        sitemapChangefreq:
            type: choice
            type_options:
                required: false
                choices:
                    admin_page.form.indexing.sitemapChangefreq.values.empty: ''
                    admin_page.form.indexing.sitemapChangefreq.values.always: always
                    admin_page.form.indexing.sitemapChangefreq.values.hourly: hourly
                    admin_page.form.indexing.sitemapChangefreq.values.daily: daily
                    admin_page.form.indexing.sitemapChangefreq.values.weekly: weekly
                    admin_page.form.indexing.sitemapChangefreq.values.monthly: monthly
                    admin_page.form.indexing.sitemapChangefreq.values.yearly: yearly
                    admin_page.form.indexing.sitemapChangefreq.values.never: never                
        sitemapPriority:
            type: number
            type_options:
                required: false
                scale: 1
                constraints:
                    - { constraint: range, options: { min: 0, max: 1 } }
