list:
    controller: sfs_cms.admin.content.controller::list
    path: /

create:
    controller: sfs_cms.admin.content.controller::create
    path: /create

import:
    controller: sfs_cms.admin.content.controller::create
    path: /import
    defaults:
        configKey: 'import'

details:
    controller: sfs_cms.admin.content.controller::read
    path: /{content}

update:
    controller: sfs_cms.admin.content.controller::update
    path: /{content}/update

duplicate:
    controller: sfs_cms.admin.content.controller::update
    path: /{content}/duplicate
    defaults:
        configKey: 'duplicate'

routes:
    controller: sfs_cms.admin.content.controller::update
    path: /{content}/routes
    defaults:
        configKey: 'routes'

delete:
    controller: sfs_cms.admin.content.controller::delete
    path: /{content}/delete

unpublish:
    controller: sfs_cms.admin.content.controller::apply
    path: /{content}/unpublish
    defaults:
        configKey: 'unpublish'

preview:
    controller: sfs_cms.admin.content.controller::read
    path: /{content}/preview
    defaults:
        configKey: 'preview'

content:
    controller: sfs_cms.admin.content_version.controller::create
    path: /{content}/content
    defaults:
        configKey: 'version_create'

content_from_version:
    controller: sfs_cms.admin.content_version.controller::create
    path: /{content}/{prevVersion}/content
    defaults:
        configKey: 'version_create'

versions:
    controller: sfs_cms.admin.content_version.controller::list
    path: /{content}/versions
    defaults:
        configKey: 'version_list'

keep_version:
    controller: sfs_cms.admin.content_version.controller::apply
    path: /{content}/{version}/keep-version
    defaults:
        configKey: 'version_lock'
        lock: true

unkeep_version:
    controller: sfs_cms.admin.content_version.controller::apply
    path: /{content}/{version}/unkeep-version
    defaults:
        configKey: 'version_lock'
        lock: false

recompile_version:
    controller: sfs_cms.admin.content_version.controller::apply
    path: /{content}/{version}/recompile
    defaults:
        configKey: 'version_recompile'

version_preview:
    controller: sfs_cms.admin.content_version.controller::read
    path: /{content}/{version}/preview
    defaults:
        configKey: 'version_preview'

publish_version:
    controller: sfs_cms.admin.content_version.controller::apply
    path: /{content}/{version}/publish
    defaults:
        configKey: 'version_publish'

export_version:
    controller: sfs_cms.admin.content_version.controller::apply
    path: /{content}/{version}/export
    defaults:
        configKey: 'version_export'

version_info:
    controller: sfs_cms.admin.content_version.controller::update
    path: /{content}/{version}/info
    defaults:
        configKey: 'version_info'

import_version:
    controller: sfs_cms.admin.content_version.controller::create
    path: /{content}/import
    defaults:
        configKey: 'version_import'

cleanup_versions:
    controller: sfs_cms.admin.content_version.controller::apply
    path: /{content}/versions-cleanup
    defaults:
        configKey: 'version_cleanup'

seo:
    controller: sfs_cms.admin.content_version.controller::create
    path: /{content}/seo
    defaults:
        configKey: 'version_seo'

seo_version:
    controller: sfs_cms.admin.content_version.controller::create
    path: /{content}/{version}/seo
    defaults:
        configKey: 'version_seo'

delete_version:
    controller: sfs_cms.admin.content_version.controller::delete
    path: /{content}/{version}/delete
    defaults:
        configKey: 'version_delete'

_plugin_routes:
    resource: '.'
    type: sfs_cms_plugin_admin_content_type