sfs_cms_admin_menus_list:
    controller: sfs_cms.admin.menu.controller::list
    path: /

sfs_cms_admin_menus_create:
    controller: sfs_cms.admin.menu.controller::create
    path: /create/{menuType}

sfs_cms_admin_menus_update:
    controller: sfs_cms.admin.menu.controller::update
    path: /{menu}/update

#sfs_cms_admin_menus_delete:
#    controller: Softspring\CmsBundle\Controller\Admin\MenuController::delete
#    path: /{menu}/delete
