sfs_cms_admin_blocks_list:
    controller: sfs_cms.admin.block.controller::list
    path: /

sfs_cms_admin_blocks_create:
    controller: sfs_cms.admin.block.controller::create
    path: /create/{blockType}

sfs_cms_admin_blocks_update:
    controller: sfs_cms.admin.block.controller::update
    path: /{block}/update
