Softspring\CmsBundle\Model\ContentInterface:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    
    getters:
        routes:
            - Valid: ~
        canonicalPage:
            -   Symfony\Component\Validator\Constraints\Expression:
                    expression: "this.getCanonicalPage() == null or this.getCanonicalPage() != this"
                    message: "Canonical page cannot reference itself"
