module:
    revision: 2
    group: 'html'
    edit_template: '@module/html_translatable/edit.html.twig'
    render_template: '@module/html_translatable/render.html.twig'
    form_template: '@module/html_translatable/form.html.twig'
    module_options:
        label_format: 'modules.html_translatable.%%name%%.label'
        translation_domain: 'custom_domain'
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            code:
                type: 'translatable'
                type_options:
                    type: 'html'
                    type_options:
                        attr:
                            style: 'min-height: 400px'
