module:
    revision: 1
    group: 'cms-blocks'
    edit_template: '@module/section/edit.html.twig'
    form_template: '@module/section/form.html.twig'
    render_template: '@module/section/render.html.twig'
    module_options:
        label_format: 'modules.section.%%name%%.label'
        translation_domain: 'custom_domain'
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            section:
                type: 'section'

            mode:
                type: 'choice'
                type_options:
                    choices:
                        section.form.mode.choices.embedded: 'embedded'
                        section.form.mode.choices.esi: 'esi'
                        section.form.mode.choices.ajax: 'ajax'
                    required: true
                    expanded: false
                    multiple: false

