security:
    role_hierarchy:

        ROLE_SFS_CMS_ADMIN_SITES_RO:
            - PERMISSION_SFS_CMS_ADMIN_SITES_LIST
            - PERMISSION_SFS_CMS_ADMIN_SITES_DETAILS

        ROLE_SFS_CMS_ADMIN_BLOCKS_RO:
            - PERMISSION_SFS_CMS_ADMIN_BLOCKS_LIST
            - PERMISSION_SFS_CMS_ADMIN_BLOCKS_DETAILS
        ROLE_SFS_CMS_ADMIN_BLOCKS_RW:
            - ROLE_SFS_CMS_ADMIN_BLOCKS_RO
            - PERMISSION_SFS_CMS_ADMIN_BLOCKS_CREATE
            - PERMISSION_SFS_CMS_ADMIN_BLOCKS_DELETE
            - PERMISSION_SFS_CMS_ADMIN_BLOCKS_UPDATE

        ROLE_SFS_CMS_ADMIN_ROUTES_RO:
            - PERMISSION_SFS_CMS_ADMIN_ROUTES_LIST
            - PERMISSION_SFS_CMS_ADMIN_ROUTES_DETAILS
        ROLE_SFS_CMS_ADMIN_ROUTES_RW:
            - ROLE_SFS_CMS_ADMIN_ROUTES_RO
            - PERMISSION_SFS_CMS_ADMIN_ROUTES_CREATE
            - PERMISSION_SFS_CMS_ADMIN_ROUTES_DELETE
            - PERMISSION_SFS_CMS_ADMIN_ROUTES_UPDATE

        ROLE_SFS_CMS_ADMIN_MENUS_RO:
            - PERMISSION_SFS_CMS_ADMIN_MENUS_LIST
        ROLE_SFS_CMS_ADMIN_MENUS_RW:
            - ROLE_SFS_CMS_ADMIN_MENUS_RO
            - PERMISSION_SFS_CMS_ADMIN_MENUS_CREATE
            - PERMISSION_SFS_CMS_ADMIN_MENUS_DELETE
            - PERMISSION_SFS_CMS_ADMIN_MENUS_UPDATE

        ROLE_SFS_CMS_ADMIN_CONTENTS_RO:
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_LIST
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_READ
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_PREVIEW
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_VERSIONS
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_EXPORT_VERSION
        ROLE_SFS_CMS_ADMIN_CONTENTS_CREATOR:
            - ROLE_SFS_CMS_ADMIN_CONTENTS_RO
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_CREATE
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_IMPORT
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_IMPORT_VERSION
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_CONTENT
        ROLE_SFS_CMS_ADMIN_CONTENTS_PUBLISHER:
            - ROLE_SFS_CMS_ADMIN_CONTENTS_CREATOR
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_UPDATE
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_DELETE
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_SEO
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_CLEANUP_VERSIONS
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_KEEP_VERSION
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_PUBLISH_VERSION
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_UNPUBLISH
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_VERSION_INFO
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_RECOMPILE_VERSION
        ROLE_SFS_CMS_ADMIN_CONTENTS_RW:
            - ROLE_SFS_CMS_ADMIN_CONTENTS_PUBLISHER

        # DEPRECATED ROLES, WILL BE REMOVED IN 6.0
        # 5.1 REQUIRES PERMISSIONS-BUNDLE
        PERMISSION_SFS_CMS_ADMIN_BLOCKS_LIST:
            - ROLE_SFS_CMS_ADMIN_BLOCKS_LIST
        PERMISSION_SFS_CMS_ADMIN_BLOCKS_DETAILS:
            - ROLE_SFS_CMS_ADMIN_BLOCKS_DETAILS
        PERMISSION_SFS_CMS_ADMIN_BLOCKS_CREATE:
            - ROLE_SFS_CMS_ADMIN_BLOCKS_CREATE
        PERMISSION_SFS_CMS_ADMIN_BLOCKS_DELETE:
            - ROLE_SFS_CMS_ADMIN_BLOCKS_DELETE
        PERMISSION_SFS_CMS_ADMIN_BLOCKS_UPDATE:
            - ROLE_SFS_CMS_ADMIN_BLOCKS_UPDATE
        PERMISSION_SFS_CMS_ADMIN_ROUTES_LIST:
            - ROLE_SFS_CMS_ADMIN_ROUTES_LIST
        PERMISSION_SFS_CMS_ADMIN_ROUTES_DETAILS:
            - ROLE_SFS_CMS_ADMIN_ROUTES_DETAILS
        PERMISSION_SFS_CMS_ADMIN_ROUTES_CREATE:
            - ROLE_SFS_CMS_ADMIN_ROUTES_CREATE
        PERMISSION_SFS_CMS_ADMIN_ROUTES_DELETE:
            - ROLE_SFS_CMS_ADMIN_ROUTES_DELETE
        PERMISSION_SFS_CMS_ADMIN_ROUTES_UPDATE:
            - ROLE_SFS_CMS_ADMIN_ROUTES_UPDATE
        PERMISSION_SFS_CMS_ADMIN_MENUS_LIST:
            - ROLE_SFS_CMS_ADMIN_MENUS_LIST
        PERMISSION_SFS_CMS_ADMIN_MENUS_CREATE:
            - ROLE_SFS_CMS_ADMIN_MENUS_CREATE
        PERMISSION_SFS_CMS_ADMIN_MENUS_DELETE:
            - ROLE_SFS_CMS_ADMIN_MENUS_DELETE
        PERMISSION_SFS_CMS_ADMIN_MENUS_UPDATE:
            - ROLE_SFS_CMS_ADMIN_MENUS_UPDATE
        PERMISSION_SFS_CMS_ADMIN_CONTENT_LIST:
            - ROLE_SFS_CMS_ADMIN_PAGES_LIST
        PERMISSION_SFS_CMS_ADMIN_CONTENT_DETAILS:
            - ROLE_SFS_CMS_ADMIN_PAGES_DETAILS
        PERMISSION_SFS_CMS_ADMIN_CONTENT_CREATE:
            - ROLE_SFS_CMS_ADMIN_PAGES_CREATE
        PERMISSION_SFS_CMS_ADMIN_CONTENT_DELETE:
            - ROLE_SFS_CMS_ADMIN_PAGES_DELETE
        PERMISSION_SFS_CMS_ADMIN_CONTENT_UPDATE:
            - ROLE_SFS_CMS_ADMIN_PAGES_UPDATE
        ROLE_SFS_CMS_ADMIN_PAGES_RO:
            - ROLE_SFS_CMS_ADMIN_CONTENTS_RO
        ROLE_SFS_CMS_ADMIN_PAGES_RW:
            - ROLE_SFS_CMS_ADMIN_PAGES_RO
            - ROLE_SFS_CMS_ADMIN_CONTENTS_RW